# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/code/RFC-8439-fpga-implementation/AES-Cam-on-PYNQ-Z2-main/AES-Cam-on-PYNQ-Z2-main/AES_SYS/AES_SYS.srcs/sources_1/bd/AES_SYS/ip/AES_SYS_axi_gpio_3_1/AES_SYS_axi_gpio_3_1.xci
# IP: The module: 'AES_SYS_axi_gpio_3_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/code/RFC-8439-fpga-implementation/AES-Cam-on-PYNQ-Z2-main/AES-Cam-on-PYNQ-Z2-main/AES_SYS/AES_SYS.gen/sources_1/bd/AES_SYS/ip/AES_SYS_axi_gpio_3_1/AES_SYS_axi_gpio_3_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_SYS_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/code/RFC-8439-fpga-implementation/AES-Cam-on-PYNQ-Z2-main/AES-Cam-on-PYNQ-Z2-main/AES_SYS/AES_SYS.gen/sources_1/bd/AES_SYS/ip/AES_SYS_axi_gpio_3_1/AES_SYS_axi_gpio_3_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_SYS_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/code/RFC-8439-fpga-implementation/AES-Cam-on-PYNQ-Z2-main/AES-Cam-on-PYNQ-Z2-main/AES_SYS/AES_SYS.gen/sources_1/bd/AES_SYS/ip/AES_SYS_axi_gpio_3_1/AES_SYS_axi_gpio_3_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_SYS_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/code/RFC-8439-fpga-implementation/AES-Cam-on-PYNQ-Z2-main/AES-Cam-on-PYNQ-Z2-main/AES_SYS/AES_SYS.srcs/sources_1/bd/AES_SYS/ip/AES_SYS_axi_gpio_3_1/AES_SYS_axi_gpio_3_1.xci
# IP: The module: 'AES_SYS_axi_gpio_3_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/code/RFC-8439-fpga-implementation/AES-Cam-on-PYNQ-Z2-main/AES-Cam-on-PYNQ-Z2-main/AES_SYS/AES_SYS.gen/sources_1/bd/AES_SYS/ip/AES_SYS_axi_gpio_3_1/AES_SYS_axi_gpio_3_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_SYS_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/code/RFC-8439-fpga-implementation/AES-Cam-on-PYNQ-Z2-main/AES-Cam-on-PYNQ-Z2-main/AES_SYS/AES_SYS.gen/sources_1/bd/AES_SYS/ip/AES_SYS_axi_gpio_3_1/AES_SYS_axi_gpio_3_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_SYS_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/code/RFC-8439-fpga-implementation/AES-Cam-on-PYNQ-Z2-main/AES-Cam-on-PYNQ-Z2-main/AES_SYS/AES_SYS.gen/sources_1/bd/AES_SYS/ip/AES_SYS_axi_gpio_3_1/AES_SYS_axi_gpio_3_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_SYS_axi_gpio_3_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
