# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/AES_SYS/AES_SYS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS || ORIG_REF_NAME==AES_SYS} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_processing_system7_0_0/AES_SYS_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_processing_system7_0_0 || ORIG_REF_NAME==AES_SYS_processing_system7_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_vdma_0_0/AES_SYS_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_vdma_0_0 || ORIG_REF_NAME==AES_SYS_axi_vdma_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_v_tc_0_0/AES_SYS_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_v_tc_0_0 || ORIG_REF_NAME==AES_SYS_v_tc_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_v_axi4s_vid_out_0_0/AES_SYS_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==AES_SYS_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_rgb2dvi_0_0/AES_SYS_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_rgb2dvi_0_0 || ORIG_REF_NAME==AES_SYS_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_clk_wiz_0_0/AES_SYS_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_clk_wiz_0_0 || ORIG_REF_NAME==AES_SYS_clk_wiz_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_intc_0_0/AES_SYS_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_intc_0_0 || ORIG_REF_NAME==AES_SYS_axi_intc_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_xlconcat_0_0/AES_SYS_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_xlconcat_0_0 || ORIG_REF_NAME==AES_SYS_xlconcat_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_xbar_0/AES_SYS_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_xbar_0 || ORIG_REF_NAME==AES_SYS_xbar_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_ps7_0_axi_periph_0/AES_SYS_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_ps7_0_axi_periph_0 || ORIG_REF_NAME==AES_SYS_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_rst_ps7_0_100M_0/AES_SYS_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_rst_ps7_0_100M_0 || ORIG_REF_NAME==AES_SYS_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_xbar_1/AES_SYS_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_xbar_1 || ORIG_REF_NAME==AES_SYS_xbar_1} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_mem_intercon_0/AES_SYS_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_mem_intercon_0 || ORIG_REF_NAME==AES_SYS_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_xlconstant_0_0/AES_SYS_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_xlconstant_0_0 || ORIG_REF_NAME==AES_SYS_xlconstant_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_gpio_0_0/AES_SYS_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_gpio_0_0 || ORIG_REF_NAME==AES_SYS_axi_gpio_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_cdma_0_0/AES_SYS_axi_cdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_cdma_0_0 || ORIG_REF_NAME==AES_SYS_axi_cdma_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_xbar_2/AES_SYS_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_xbar_2 || ORIG_REF_NAME==AES_SYS_xbar_2} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_mem_intercon_1_0/AES_SYS_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_mem_intercon_1_0 || ORIG_REF_NAME==AES_SYS_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_bram_ctrl_0_0/AES_SYS_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_bram_ctrl_0_0 || ORIG_REF_NAME==AES_SYS_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_bram_ctrl_0_bram_0/AES_SYS_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==AES_SYS_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_gpio_5_0/AES_SYS_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_gpio_5_0 || ORIG_REF_NAME==AES_SYS_axi_gpio_5_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_gpio_6_0/AES_SYS_axi_gpio_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_gpio_6_0 || ORIG_REF_NAME==AES_SYS_axi_gpio_6_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_gpio_8_0/AES_SYS_axi_gpio_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_gpio_8_0 || ORIG_REF_NAME==AES_SYS_axi_gpio_8_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_gpio_10_0/AES_SYS_axi_gpio_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_gpio_10_0 || ORIG_REF_NAME==AES_SYS_axi_gpio_10_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_RFC8439_0_0/AES_SYS_RFC8439_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_RFC8439_0_0 || ORIG_REF_NAME==AES_SYS_RFC8439_0_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_gpio_1_1/AES_SYS_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_gpio_1_1 || ORIG_REF_NAME==AES_SYS_axi_gpio_1_1} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_gpio_2_1/AES_SYS_axi_gpio_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_gpio_2_1 || ORIG_REF_NAME==AES_SYS_axi_gpio_2_1} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_gpio_3_1/AES_SYS_axi_gpio_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_gpio_3_1 || ORIG_REF_NAME==AES_SYS_axi_gpio_3_1} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_bram_ctrl_0_bram_2/AES_SYS_axi_bram_ctrl_0_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_bram_ctrl_0_bram_2 || ORIG_REF_NAME==AES_SYS_axi_bram_ctrl_0_bram_2} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_axi_bram_ctrl_0_2/AES_SYS_axi_bram_ctrl_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_axi_bram_ctrl_0_2 || ORIG_REF_NAME==AES_SYS_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_11/AES_SYS_auto_pc_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_11 || ORIG_REF_NAME==AES_SYS_auto_pc_11} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_0/AES_SYS_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_0 || ORIG_REF_NAME==AES_SYS_auto_pc_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_1/AES_SYS_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_1 || ORIG_REF_NAME==AES_SYS_auto_pc_1} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_2/AES_SYS_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_2 || ORIG_REF_NAME==AES_SYS_auto_pc_2} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_3/AES_SYS_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_3 || ORIG_REF_NAME==AES_SYS_auto_pc_3} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_4/AES_SYS_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_4 || ORIG_REF_NAME==AES_SYS_auto_pc_4} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_5/AES_SYS_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_5 || ORIG_REF_NAME==AES_SYS_auto_pc_5} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_6/AES_SYS_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_6 || ORIG_REF_NAME==AES_SYS_auto_pc_6} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_7/AES_SYS_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_7 || ORIG_REF_NAME==AES_SYS_auto_pc_7} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_8/AES_SYS_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_8 || ORIG_REF_NAME==AES_SYS_auto_pc_8} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_9/AES_SYS_auto_pc_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_9 || ORIG_REF_NAME==AES_SYS_auto_pc_9} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_10/AES_SYS_auto_pc_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_10 || ORIG_REF_NAME==AES_SYS_auto_pc_10} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_12/AES_SYS_auto_pc_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_12 || ORIG_REF_NAME==AES_SYS_auto_pc_12} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_us_0/AES_SYS_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_us_0 || ORIG_REF_NAME==AES_SYS_auto_us_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_pc_13/AES_SYS_auto_pc_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_pc_13 || ORIG_REF_NAME==AES_SYS_auto_pc_13} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_ds_0/AES_SYS_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_ds_0 || ORIG_REF_NAME==AES_SYS_auto_ds_0} -quiet] -quiet

# IP: bd/AES_SYS/ip/AES_SYS_auto_ds_1/AES_SYS_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_SYS_auto_ds_1 || ORIG_REF_NAME==AES_SYS_auto_ds_1} -quiet] -quiet

# XDC: c:/code/RFC-8439-fpga-implementation/AES-Cam-on-PYNQ-Z2-main/AES-Cam-on-PYNQ-Z2-main/AES_SYS/AES_SYS.gen/sources_1/bd/AES_SYS/AES_SYS_ooc.xdc
