# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/kartg/Desktop/Github/AES-Cam on PYNQ-Z2/AES_SYS/AES_SYS.srcs/sources_1/bd/AES_SYS/ip/AES_SYS_v_axi4s_vid_out_0_0/AES_SYS_v_axi4s_vid_out_0_0.xci
# IP: The module: 'AES_SYS_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kartg/Desktop/Github/AES-Cam on PYNQ-Z2/AES_SYS/AES_SYS.gen/sources_1/bd/AES_SYS/ip/AES_SYS_v_axi4s_vid_out_0_0/AES_SYS_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_SYS_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/kartg/Desktop/Github/AES-Cam on PYNQ-Z2/AES_SYS/AES_SYS.gen/sources_1/bd/AES_SYS/ip/AES_SYS_v_axi4s_vid_out_0_0/AES_SYS_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_SYS_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/kartg/Desktop/Github/AES-Cam on PYNQ-Z2/AES_SYS/AES_SYS.srcs/sources_1/bd/AES_SYS/ip/AES_SYS_v_axi4s_vid_out_0_0/AES_SYS_v_axi4s_vid_out_0_0.xci
# IP: The module: 'AES_SYS_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kartg/Desktop/Github/AES-Cam on PYNQ-Z2/AES_SYS/AES_SYS.gen/sources_1/bd/AES_SYS/ip/AES_SYS_v_axi4s_vid_out_0_0/AES_SYS_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_SYS_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/kartg/Desktop/Github/AES-Cam on PYNQ-Z2/AES_SYS/AES_SYS.gen/sources_1/bd/AES_SYS/ip/AES_SYS_v_axi4s_vid_out_0_0/AES_SYS_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_SYS_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
